apiVersion: v1
kind: PersistentVolume
metadata:
  name: dependency-track-pv-volume-apiserver
  labels: 
    type: local
spec:
  # storageClassName: default
  capacity: 
    storage: 8Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/dependency-track/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-k8s-node-6
          - i-k8s-node-7
          - i-k8s-node-8
          - i-k8s-node-9
          - i-k8s-node-10

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dependency-track-pv-volume-postgres
  labels: 
    type: local
spec:
  # storageClassName: default
  capacity: 
    storage: 8Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/dependency-track/postgres"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-k8s-node-6
          - i-k8s-node-7
          - i-k8s-node-8
          - i-k8s-node-9
          - i-k8s-node-10