apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
data:
  config.yml: |-
    dynamic:
      config:
        enabled: true
    spring:
      security:
        oauth2:
    auth:
      type: OAUTH2
      oauth2:
        client:
          keycloak:
            clientId: kafka-ui
            scope: openid
            issuer-uri: https://id.universphere.cloud/realms/master
            user-name-attribute: preferred_username
            client-name: keycloak
            provider: keycloak
            custom-params:
              type: oauth
              roles-field: groups
    management:
      health:
        ldap:
          enabled: false