- name: create folder structure for sonarqube
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "k8s"
    group: "k8s"
    state: directory
    mode: '0700'
  loop:
    - "/mnt/sonarqube/postgres"