---
# tasks file for roles/haproxy
- name: Ensure HAProxy is installed
  become: true
  become_user: "root"
  apt:
    name:
      - haproxy
    update_cache: yes
    state: present

- name: Set haproxy.cfg
  become: true
  become_user: "root"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Check HAProxy config
  become: true
  become_user: "root"
  shell: haproxy -c -f /etc/haproxy/haproxy.cfg
  register: haproxy_check
  failed_when: haproxy_check.rc != 0

- name: Restart HAProxy
  become: true
  become_user: "root"
  service:
      name: haproxy
      state: restarted
