apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    replicas: 1
    version: 3.6.0
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
      resources:
       requests:
         memory: 8Gi
         cpu: "1"
       limits:
         memory: 16Gi
         cpu: "2"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 8192m
      -Xmx: 8192m
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: internal-tls
        port: 9093
        type: internal
        tls: true
        configuration:
          useServiceDnsDomain: true
        authentication:
          type: tls
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: persistent-claim
      size: 10Gi
      selector:
        - app: kafka
  zookeeper:
    replicas: 3
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: INFO
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "1"
    jvmOptions:
      -Xms: 4096m 
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 5Gi
      selector:
        - app: kafka
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    topicOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: "1"
