apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
spec:
  kafka:
    replicas: 1
    version: 3.6.0
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
    # resources:
    #   requests:
    #     memory: 2Gi
    #     cpu: "1"
    #   limits:
    #     memory: 2Gi
    #     cpu: "1"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
#    image: my-org/my-image:latest
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
        configuration:
          useServiceDnsDomain: true
        authentication:
          type: tls
      - name: nodeport
        port: 9095
        type: nodeport
        tls: false
        configuration:
          preferredNodePortAddressType: InternalDNS
      - name: nodeporttls
        port: 9096
        type: nodeport
        tls: true
        authentication:
          type: tls
        configuration:
          preferredNodePortAddressType: InternalDNS
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: persistent-claim
      size: 1Gi
#    rack:
#      topologyKey: topology.kubernetes.io/zone
#    metricsConfig:
#      type: jmxPrometheusExporter
#      valueFrom:
#        configMapKeyRef:
#          name: my-config-map
#          key: my-key
    # ...
  zookeeper:
    replicas: 1
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: INFO
#    resources:
#      requests:
#        memory: 1Gi
#        cpu: "1"
#      limits:
#        memory: 1Gi
#        cpu: "1"
    jvmOptions:
      -Xms: 4096m 
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 1Gi
#    metricsConfig:
    # ...
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    topicOperator:
      watchedNamespace: default
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      watchedNamespace: default
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
