apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: universphere-secure
  labels:
    strimzi.io/cluster: my-kafka
spec:
  partitions: 1
  replicas: 1
#  config:
#    retention.ms: 7200000
#    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: universphere-insecure
  labels:
    strimzi.io/cluster: my-kafka
spec:
  partitions: 1
  replicas: 1