- name: create folder structure for persistant volumes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "k8s"
    group: "k8s"
    state: directory
    mode: '0700'
  with_items:
    - "{{ mountPoints }}"